<?php
    class ErrorCodes
    {
	const OK = 0;
        const SYSTEM_FAULT = 100;
        const SYSTEM_INITIALIZATION_FAIL = 101;
        CONST SYSTEM_UNKNOWN_ERROR = 199;
        
        const INVALID_REQUEST   = 200;
        CONST REQUEST_INVALID   = ErrorCodes::INVALID_REQUEST;
        CONST REQUEST_UNKNOWN_ERROR = 299;
        
        CONST SESSION_ERROR = 300;
	CONST SESSION_IS_CLOSED = 310;
        CONST SESSION_EXPIRED = ErrorCodes::SESSION_IS_CLOSED;
	const BAD_SESSION = 311;
        CONST SESSION_BAD_DATA = 312;
	CONST SESSION_UNKNOWN_ERROR = 399;
	        
        const INVALID_OPERATION = 400;
	CONST OPERATION_INVALID = ErrorCodes::INVALID_OPERATION;
        const OPERATION_FAIL    = 401; 
	const OPERATION_UNSUPPORTED = 402;
        const OPERATION_UNAVAILIBLE = 403;
	const OPERATION_PARAMETERS_MISMATCH = 404;
	const OPERATION_BAD_DATA = 405;
	const OPERATION_BAD_USER_TYPE = 406;
	const OPERATION_LOGIN_BAD_LOGIN_DATA = 411;
	const OPERATION_REGISTRATE_BAD_KEY = 421;
	const OPERATION_REGISTRATE_LOGIN_ALREADY_EXISTS = 422;
	const OPERATION_REGISTRATE_MAIL_ALREADY_EXISTS = 423;
	const OPERATION_REGISTRATE_PHONE_ALREADY_EXISTS = 424;
	const OPERATION_REGISTRATE_BAD_DATA = 425;
	const OPERATION_REGISTRATE_LMP_ALREADY_EXISTS = 426;
        const OPERATION_LINK_EXPIRED = 440;
        const OPERATION_CONDITION_INCONSISTENCY = 450;
        const OPERATION_REQUEST_EXPIRED_OR_CLOSED = 460;
	const OPERATION_UNKNOWN_ERROR = 499;
	
        CONST USER_ERROR = 500;
	CONST USER_NO_RIGHTS = 501;
        CONST USER_CONDITION_VIOLATION = 502;
        CONST USER_UNKNOWN_ERROR = 599;
        
        CONST NO_RIGHTS = ErrorCodes::USER_NO_RIGHTS;
        
        CONST UNKNOWN_ERROR = 999;
    }
?>