<?php
	class ErrorCodes
	{
		const OK = 0;
		const INVALID_REQUEST   = 100;
		const INVALID_OPERATION = 110;
		const OPERATION_FAIL    = 111; 
		const OPERATION_UNSUPPORTED = 112;
		const OPERATION_PARAMETERS_MISMATCH = 121;
		const OPERATION_BAD_DATA = 122;
		const OPERATION_BAD_USER_TYPE = 151;
		const OPERATION_LOGIN_BAD_LOGIN_DATA = 161;
		const OPERATION_REGISTRATE_BAD_KEY = 171;
		const OPERATION_REGISTRATE_LOGIN_ALREADY_EXISTS = 172;
		const OPERATION_REGISTRATE_MAIL_ALREADY_EXISTS = 173;
		const OPERATION_REGISTRATE_PHONE_ALREADY_EXISTS = 174;
		const OPERATION_REGISTRATE_BAD_DATA = 175;
		const OPERATION_REGISTRATE_LMP_ALREADY_EXISTS = 178;
		const OPERATION_UNKNOWN_ERROR = 199;
		const INITIALIZATION_FAIL = 200;
		CONST SESSION_IS_CLOSED = 210;
		CONST SESSION_BAD_DATA = 211;
		CONST SESSION_UNKNOWN_ERROR = 219;
		const BAD_SESSION = 201;
		const NO_RIGHTS =   202;
	}
?>